### ISSUE TITLE
unexpected error on tx submit from multiple runs of next.jdbc test suite

### ISSUE THREAD

**Issue by seancorfield** [xtdb/crux#3894]
As I'm working on getting all the `next.jdbc` tests passing on XTDB (or at least disabling tests that cannot work... yet), I'm finding that if I run my failing test suite multiple times, after a few runs I get this error:
```Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2733).
ERROR: unexpected error on tx submit (report as a bug)
```
(stacktrace in :thread: )

[Slack Message](https://clojurians.slack.com/archives/CG3AM2F7V/p1732464984372129?thread_ts=1732464984.372129&cid=CG3AM2F7V)

EDIT (with Slack thread contents):
```
It happens in different places on different runs, but once XTDB gets into this state, the only solution is to shutdown the Docker instance and restart it (and sometimes I need to rm the container and recreate it).

{:clojure.main/message
 "Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2733).\nERROR: unexpected error on tx submit (report as a bug)\n",
 :clojure.main/triage
 {:clojure.error/class org.postgresql.util.PSQLException,
  :clojure.error/line 2733,
  :clojure.error/cause
  "ERROR: unexpected error on tx submit (report as a bug)",
  :clojure.error/symbol
  org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse,
  :clojure.error/source "QueryExecutorImpl.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type org.postgresql.util.PSQLException,
    :message "ERROR: unexpected error on tx submit (report as a bug)",
    :at
    [org.postgresql.core.v3.QueryExecutorImpl
     receiveErrorResponse
     "QueryExecutorImpl.java"
     2733]}],
  :trace
  [[org.postgresql.core.v3.QueryExecutorImpl
    receiveErrorResponse
    "QueryExecutorImpl.java"
    2733]
   [org.postgresql.core.v3.QueryExecutorImpl
    processResults
    "QueryExecutorImpl.java"
    2420]
   [org.postgresql.core.v3.QueryExecutorImpl
    execute
    "QueryExecutorImpl.java"
    372]
   [org.postgresql.jdbc.PgStatement
    executeInternal
    "PgStatement.java"
    517]
   [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 434]
   [org.postgresql.jdbc.PgPreparedStatement
    executeWithFlags
    "PgPreparedStatement.java"
    194]
   [org.postgresql.jdbc.PgPreparedStatement
    execute
    "PgPreparedStatement.java"
    180]
   [next.jdbc.result_set$stmt__GT_result_set
    invokeStatic
    "result_set.clj"
    667]
   [next.jdbc.result_set$stmt__GT_result_set
    invoke
    "result_set.clj"
    662]
   [next.jdbc.result_set$eval4022$fn__4030 invoke "result_set.clj" 895]
   [next.jdbc.protocols$eval2653$fn__2684$G__2644__2693
    invoke
    "protocols.clj"
    34]
   [next.jdbc$execute_BANG_ invokeStatic "jdbc.clj" 258]
   [next.jdbc$execute_BANG_ invoke "jdbc.clj" 242]
   [clojure.lang.AFn applyToHelper "AFn.java" 160]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.spec.test.alpha$spec_checking_fn$fn__3023
    doInvoke
    "alpha.clj"
    153]
   [clojure.lang.RestFn invoke "RestFn.java" 436]
   [next.jdbc.sql$insert_multi_BANG_ invokeStatic "sql.clj" 93]
   [next.jdbc.sql$insert_multi_BANG_ invoke "sql.clj" 46]
   [clojure.lang.AFn applyToHelper "AFn.java" 171]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.spec.test.alpha$spec_checking_fn$fn__3023
    doInvoke
    "alpha.clj"
    153]
   [clojure.lang.RestFn invoke "RestFn.java" 482]
   [next.jdbc.test_fixtures$with_test_db$fn__4547
    invoke
    "test_fixtures.clj"
    187]
   [next.jdbc.test_fixtures$with_test_db
    invokeStatic
    "test_fixtures.clj"
    181]
   [next.jdbc.test_fixtures$with_test_db
    invoke
    "test_fixtures.clj"
    152]
   [clojure.test$compose_fixtures$fn__9755$fn__9756
    invoke
    "test.clj"
    694]
   [clojure.test$default_fixture invokeStatic "test.clj" 687]
   [clojure.test$default_fixture invoke "test.clj" 683]
   [clojure.test$compose_fixtures$fn__9755 invoke "test.clj" 694]
   [clojure.test$test_vars$fn__9787 invoke "test.clj" 735]
   [clojure.test$default_fixture invokeStatic "test.clj" 687]
   [clojure.test$default_fixture invoke "test.clj" 683]
   [clojure.test$test_vars invokeStatic "test.clj" 731]
   [clojure.test$test_all_vars invokeStatic "test.clj" 737]
   [clojure.test$test_ns invokeStatic "test.clj" 758]
   [clojure.test$test_ns invoke "test.clj" 743]
   [clojure.core$map$fn__5884 invoke "core.clj" 2759]
   [clojure.lang.LazySeq sval "LazySeq.java" 42]
   [clojure.lang.LazySeq seq "LazySeq.java" 51]
   [clojure.lang.Cons next "Cons.java" 39]
   [clojure.lang.RT next "RT.java" 713]
   [clojure.core$next__5403 invokeStatic "core.clj" 64]
   [clojure.core$reduce1 invokeStatic "core.clj" 946]
   [clojure.core$reduce1 invokeStatic "core.clj" 936]
   [clojure.core$merge_with invokeStatic "core.clj" 3063]
   [clojure.core$merge_with doInvoke "core.clj" 3055]
   [clojure.lang.RestFn applyTo "RestFn.java" 139]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.test$run_tests invokeStatic "test.clj" 768]
   [clojure.test$run_tests doInvoke "test.clj" 768]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$apply invoke "core.clj" 662]
   [cognitect.test_runner$test invokeStatic "test_runner.clj" 74]
   [cognitect.test_runner$test invoke "test_runner.clj" 62]
   [cognitect.test_runner.api$do_test invokeStatic "api.clj" 14]
   [cognitect.test_runner.api$do_test invoke "api.clj" 6]
   [cognitect.test_runner.api$test invokeStatic "api.clj" 28]
   [cognitect.test_runner.api$test invoke "api.clj" 16]
   [clojure.lang.Var invoke "Var.java" 384]
   [clojure.run.exec$exec invokeStatic "exec.clj" 88]
   [clojure.run.exec$exec invoke "exec.clj" 78]
   [clojure.run.exec$_main$fn__220 invoke "exec.clj" 227]
   [clojure.run.exec$_main invokeStatic "exec.clj" 223]
   [clojure.run.exec$_main doInvoke "exec.clj" 191]
   [clojure.lang.RestFn invoke "RestFn.java" 397]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "ERROR: unexpected error on tx submit (report as a bug)"}}
```

> This branch has the current state of play, if you want to try for yourselves: https://github.com/seancorfield/next-jdbc/tree/xtdb-testing
> Clone the repo, checkout that branch, run docker compose up, and then run NEXT_JDBC_TEST_XTDB=yes clojure -X:test a few times.

```
xtdb-1       | 16:37:01 | ERROR xtdb.indexer | Error processing SQL transaction operation {:query "DELETE FROM fruit WHERE true"}
xtdb-1       | java.lang.UnsupportedOperationException: org.apache.arrow.vector.complex.DenseUnionVector
xtdb-1       |  at xtdb.vector.ValueVectorReader.unsupported(ValueVectorReader.java:91)
xtdb-1       |  at xtdb.vector.ValueVectorReader.getBytes(ValueVectorReader.java:136)
xtdb-1       |  at xtdb.vector.RenamedVectorReader.getBytes(RenamedVectorReader.java:95)
xtdb-1       |  at xtdb.indexer$$reify__27715.indexOp(indexer.clj:360)
xtdb-1       |  at xtdb.indexer$query_indexer$eval_query$reify__27739.accept(indexer.clj:420)
xtdb-1       |  at xtdb.operator.project.ProjectCursor$reify__24798.accept(project.clj:133)
xtdb-1       |  at xtdb.operator.project.ProjectCursor$reify__24798.accept(project.clj:133)
xtdb-1       |  at xtdb.operator.rename.RenameCursor$reify__25591.accept(rename.clj:39)
xtdb-1       |  at xtdb.coalesce.CoalescingCursor.tryAdvance(coalesce.clj:61)
xtdb-1       |  at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
xtdb-1       |  at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
xtdb-1       |  at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
xtdb-1       |  at xtdb.query$wrap_cursor$reify__27486.tryAdvance(query.clj:84)
xtdb-1       |  at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
xtdb-1       |  at xtdb.indexer$query_indexer$eval_query__27738.invoke(indexer.clj:417)
xtdb-1       |  at xtdb.indexer$wrap_sql_args$fn__27746.invoke(indexer.clj:454)
xtdb-1       |  at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:437)
xtdb-1       |  at xtdb.indexer$foreach_arg_row.invoke(indexer.clj:427)
xtdb-1       |  at xtdb.indexer$$reify__27751$fn__27752.invoke(indexer.clj:489)
xtdb-1       |  at xtdb.indexer$$reify__27751.indexOp(indexer.clj:469)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821$fn__27834.invoke(indexer.clj:647)
xtdb-1       |  at clojure.lang.AFn.call(AFn.java:18)
xtdb-1       |  at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821.invoke(indexer.clj:644)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$fn__27842.invoke(indexer.clj:658)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816.invoke(indexer.clj:657)
xtdb-1       |  at xtdb.indexer.Indexer.indexTx(indexer.clj:619)
xtdb-1       |  at xtdb.log.watcher$watch_log_BANG_$reify__29180.accept(watcher.clj:55)
xtdb-1       |  at xtdb.log$tx_handler$fn__22745.invoke(log.clj:40)
xtdb-1       |  at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
xtdb-1       |  at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
xtdb-1       |  at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
xtdb-1       |  at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
xtdb-1       |  at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
xtdb-1       |  at clojure.core$reduce.invokeStatic(core.clj:6965)
xtdb-1       |  at clojure.core$reduce.invoke(core.clj:6947)
xtdb-1       |  at xtdb.log.NotifyingSubscriberHandler$fn__22778.invoke(log.clj:99)
xtdb-1       |  at clojure.lang.AFn.run(AFn.java:22)
xtdb-1       |  at java.base/java.lang.Thread.run(Thread.java:1583)
xtdb-1       | 16:37:01 | ERROR xtdb.indexer | error in indexer, indexing #xt/tx-key {:tx-id 6815003, :system-time #time/instant "2024-11-24T16:37:01.211374Z"}
xtdb-1       | java.lang.UnsupportedOperationException: org.apache.arrow.vector.complex.DenseUnionVector
xtdb-1       |  at xtdb.vector.ValueVectorReader.unsupported(ValueVectorReader.java:91)
xtdb-1       |  at xtdb.vector.ValueVectorReader.getBytes(ValueVectorReader.java:136)
xtdb-1       |  at xtdb.vector.RenamedVectorReader.getBytes(RenamedVectorReader.java:95)
xtdb-1       |  at xtdb.indexer$$reify__27715.indexOp(indexer.clj:360)
xtdb-1       |  at xtdb.indexer$query_indexer$eval_query$reify__27739.accept(indexer.clj:420)
xtdb-1       |  at xtdb.operator.project.ProjectCursor$reify__24798.accept(project.clj:133)
xtdb-1       |  at xtdb.operator.project.ProjectCursor$reify__24798.accept(project.clj:133)
xtdb-1       |  at xtdb.operator.rename.RenameCursor$reify__25591.accept(rename.clj:39)
xtdb-1       |  at xtdb.coalesce.CoalescingCursor.tryAdvance(coalesce.clj:61)
xtdb-1       |  at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
xtdb-1       |  at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
xtdb-1       |  at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
xtdb-1       |  at xtdb.query$wrap_cursor$reify__27486.tryAdvance(query.clj:84)
xtdb-1       |  at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
xtdb-1       |  at xtdb.indexer$query_indexer$eval_query__27738.invoke(indexer.clj:417)
xtdb-1       |  at xtdb.indexer$wrap_sql_args$fn__27746.invoke(indexer.clj:454)
xtdb-1       |  at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:437)
xtdb-1       |  at xtdb.indexer$foreach_arg_row.invoke(indexer.clj:427)
xtdb-1       |  at xtdb.indexer$$reify__27751$fn__27752.invoke(indexer.clj:489)
xtdb-1       |  at xtdb.indexer$$reify__27751.indexOp(indexer.clj:469)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821$fn__27834.invoke(indexer.clj:647)
xtdb-1       |  at clojure.lang.AFn.call(AFn.java:18)
xtdb-1       |  at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821.invoke(indexer.clj:644)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$fn__27842.invoke(indexer.clj:658)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816.invoke(indexer.clj:657)
xtdb-1       |  at xtdb.indexer.Indexer.indexTx(indexer.clj:619)
xtdb-1       |  at xtdb.log.watcher$watch_log_BANG_$reify__29180.accept(watcher.clj:55)
xtdb-1       |  at xtdb.log$tx_handler$fn__22745.invoke(log.clj:40)
xtdb-1       |  at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
xtdb-1       |  at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
xtdb-1       |  at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
xtdb-1       |  at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
xtdb-1       |  at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
xtdb-1       |  at clojure.core$reduce.invokeStatic(core.clj:6965)
xtdb-1       |  at clojure.core$reduce.invoke(core.clj:6947)
xtdb-1       |  at xtdb.log.NotifyingSubscriberHandler$fn__22778.invoke(log.clj:99)
xtdb-1       |  at clojure.lang.AFn.run(AFn.java:22)
xtdb-1       |  at java.base/java.lang.Thread.run(Thread.java:1583)
xtdb-1       | 16:37:01 | ERROR xtdb.util | Uncaught exception:
xtdb-1       | java.lang.UnsupportedOperationException: org.apache.arrow.vector.complex.DenseUnionVector
xtdb-1       |  at xtdb.vector.ValueVectorReader.unsupported(ValueVectorReader.java:91)
xtdb-1       |  at xtdb.vector.ValueVectorReader.getBytes(ValueVectorReader.java:136)
xtdb-1       |  at xtdb.vector.RenamedVectorReader.getBytes(RenamedVectorReader.java:95)
xtdb-1       |  at xtdb.indexer$$reify__27715.indexOp(indexer.clj:360)
xtdb-1       |  at xtdb.indexer$query_indexer$eval_query$reify__27739.accept(indexer.clj:420)
xtdb-1       |  at xtdb.operator.project.ProjectCursor$reify__24798.accept(project.clj:133)
xtdb-1       |  at xtdb.operator.project.ProjectCursor$reify__24798.accept(project.clj:133)
xtdb-1       |  at xtdb.operator.rename.RenameCursor$reify__25591.accept(rename.clj:39)
xtdb-1       |  at xtdb.coalesce.CoalescingCursor.tryAdvance(coalesce.clj:61)
xtdb-1       |  at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
xtdb-1       |  at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
xtdb-1       |  at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
xtdb-1       |  at xtdb.query$wrap_cursor$reify__27486.tryAdvance(query.clj:84)
xtdb-1       |  at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
xtdb-1       |  at xtdb.indexer$query_indexer$eval_query__27738.invoke(indexer.clj:417)
xtdb-1       |  at xtdb.indexer$wrap_sql_args$fn__27746.invoke(indexer.clj:454)
xtdb-1       |  at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:437)
xtdb-1       |  at xtdb.indexer$foreach_arg_row.invoke(indexer.clj:427)
xtdb-1       |  at xtdb.indexer$$reify__27751$fn__27752.invoke(indexer.clj:489)
xtdb-1       |  at xtdb.indexer$$reify__27751.indexOp(indexer.clj:469)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821$fn__27834.invoke(indexer.clj:647)
xtdb-1       |  at clojure.lang.AFn.call(AFn.java:18)
xtdb-1       |  at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821.invoke(indexer.clj:644)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816$fn__27842.invoke(indexer.clj:658)
xtdb-1       |  at xtdb.indexer.Indexer$fn__27816.invoke(indexer.clj:657)
xtdb-1       |  at xtdb.indexer.Indexer.indexTx(indexer.clj:619)
xtdb-1       |  at xtdb.log.watcher$watch_log_BANG_$reify__29180.accept(watcher.clj:55)
xtdb-1       |  at xtdb.log$tx_handler$fn__22745.invoke(log.clj:40)
xtdb-1       |  at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
xtdb-1       |  at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
xtdb-1       |  at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
xtdb-1       |  at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
xtdb-1       |  at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
xtdb-1       |  at clojure.core$reduce.invokeStatic(core.clj:6965)
xtdb-1       |  at clojure.core$reduce.invoke(core.clj:6947)
xtdb-1       |  at xtdb.log.NotifyingSubscriberHandler$fn__22778.invoke(log.clj:99)
xtdb-1       |  at clojure.lang.AFn.run(AFn.java:22)
xtdb-1       |  at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by seancorfield** [comment]
This problem has returned in a recent 2.0 SNAPSHOT:
```
Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2733).
ERROR: unexpected error on tx submit (report as a bug)
```
Same repro: start up a Docker instance of XTDB v2, run the `next.jdbc` tests multiple times. How I run tests has changed:
```
NEXT_JDBC_TEST_XTDB=yes clojure -M:test:runner
```

I can't re-open this issue -- do you want me to create a new issue instead?

Here's the full stack trace:
```
{:clojure.main/message
 "Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2733).\nERROR: unexpected error on tx submit (report as a bug)\n",
 :clojure.main/triage
 {:clojure.error/class org.postgresql.util.PSQLException,
  :clojure.error/line 2733,
  :clojure.error/cause
  "ERROR: unexpected error on tx submit (report as a bug)",
  :clojure.error/symbol
  org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse,
  :clojure.error/source "QueryExecutorImpl.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type org.postgresql.util.PSQLException,
    :message "ERROR: unexpected error on tx submit (report as a bug)",
    :at
    [org.postgresql.core.v3.QueryExecutorImpl
     receiveErrorResponse
     "QueryExecutorImpl.java"
     2733]}],
  :trace
  [[org.postgresql.core.v3.QueryExecutorImpl
    receiveErrorResponse
    "QueryExecutorImpl.java"
    2733]
   [org.postgresql.core.v3.QueryExecutorImpl
    processResults
    "QueryExecutorImpl.java"
    2420]
   [org.postgresql.core.v3.QueryExecutorImpl
    execute
    "QueryExecutorImpl.java"
    372]
   [org.postgresql.jdbc.PgStatement
    executeInternal
    "PgStatement.java"
    517]
   [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 434]
   [org.postgresql.jdbc.PgPreparedStatement
    executeWithFlags
    "PgPreparedStatement.java"
    194]
   [org.postgresql.jdbc.PgPreparedStatement
    execute
    "PgPreparedStatement.java"
    180]
   [next.jdbc.result_set$stmt__GT_result_set
    invokeStatic
    "result_set.clj"
    674]
   [next.jdbc.result_set$stmt__GT_result_set
    invoke
    "result_set.clj"
    669]
   [next.jdbc.result_set$eval8735$fn__8743 invoke "result_set.clj" 902]
   [next.jdbc.protocols$eval7331$fn__7362$G__7322__7371
    invoke
    "protocols.clj"
    34]
   [next.jdbc$execute_BANG_ invokeStatic "jdbc.clj" 272]
   [next.jdbc$execute_BANG_ invoke "jdbc.clj" 254]
   [clojure.lang.AFn applyToHelper "AFn.java" 160]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.spec.test.alpha$spec_checking_fn$fn__3009
    doInvoke
    "alpha.clj"
    153]
   [clojure.lang.RestFn invoke "RestFn.java" 436]
   [next.jdbc.sql$insert_multi_BANG_ invokeStatic "sql.clj" 93]
   [next.jdbc.sql$insert_multi_BANG_ invoke "sql.clj" 46]
   [clojure.lang.AFn applyToHelper "AFn.java" 171]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.spec.test.alpha$spec_checking_fn$fn__3009
    doInvoke
    "alpha.clj"
    153]
   [clojure.lang.RestFn invoke "RestFn.java" 482]
   [next.jdbc.test_fixtures$with_test_db$fn__9269
    invoke
    "test_fixtures.clj"
    190]
   [next.jdbc.test_fixtures$with_test_db
    invokeStatic
    "test_fixtures.clj"
    181]
   [next.jdbc.test_fixtures$with_test_db
    invoke
    "test_fixtures.clj"
    152]
   [next.jdbc.connection_string_test$eval9376$around__5293__auto____9377
    invoke
    "connection_string_test.clj"
    20]
   [clojure.test$compose_fixtures$fn__9755$fn__9756
    invoke
    "test.clj"
    694]
   [clojure.test$default_fixture invokeStatic "test.clj" 687]
   [clojure.test$default_fixture invoke "test.clj" 683]
   [clojure.test$compose_fixtures$fn__9755 invoke "test.clj" 694]
   [lazytest.runner$__GT_suite_result$with_around__5825
    invoke
    "runner.clj"
    30]
   [lazytest.runner$__GT_suite_result invokeStatic "runner.clj" 35]
   [lazytest.runner$__GT_suite_result invoke "runner.clj" 21]
   [lazytest.runner$eval5841$run_test__lazytest_ns__5842
    invoke
    "runner.clj"
    56]
   [clojure.lang.MultiFn invoke "MultiFn.java" 234]
   [lazytest.runner$__GT_suite_result$f__5831 invoke "runner.clj" 34]
   [clojure.core$keep$fn__8582 invoke "core.clj" 7339]
   [clojure.lang.LazySeq sval "LazySeq.java" 42]
   [clojure.lang.LazySeq seq "LazySeq.java" 51]
   [clojure.lang.RT seq "RT.java" 535]
   [clojure.lang.LazilyPersistentVector
    create
    "LazilyPersistentVector.java"
    44]
   [clojure.core$vec invokeStatic "core.clj" 379]
   [clojure.core$vec invoke "core.clj" 369]
   [lazytest.runner$__GT_suite_result$fn__5833 invoke "runner.clj" 35]
   [lazytest.runner$__GT_suite_result$fn__5829 invoke "runner.clj" 32]
   [lazytest.runner$__GT_suite_result invokeStatic "runner.clj" 35]
   [lazytest.runner$__GT_suite_result invoke "runner.clj" 21]
   [lazytest.runner$eval5837$run_test__lazytest_run__5838
    invoke
    "runner.clj"
    46]
   [clojure.lang.MultiFn invoke "MultiFn.java" 234]
   [lazytest.runner$filter_and_run invokeStatic "runner.clj" 109]
   [lazytest.runner$filter_and_run invoke "runner.clj" 104]
   [lazytest.runner$run_tests invokeStatic "runner.clj" 116]
   [lazytest.runner$run_tests invoke "runner.clj" 111]
   [lazytest.main$run_impl invokeStatic "main.clj" 45]
   [lazytest.main$run_impl invoke "main.clj" 42]
   [lazytest.main$run invokeStatic "main.clj" 56]
   [lazytest.main$run invoke "main.clj" 47]
   [lazytest.main$_main invokeStatic "main.clj" 65]
   [lazytest.main$_main doInvoke "main.clj" 62]
   [clojure.lang.RestFn invoke "RestFn.java" 397]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "ERROR: unexpected error on tx submit (report as a bug)"}}
```

**Comment by seancorfield** [comment]
Here's the XTDB console log when this happens:
```
xtdb-1       | 00:40:26 | ERROR o.apache.arrow.memory.BaseAllocator | Memory was leaked by query. Memory leaked: (53248)
xtdb-1       | Allocator(pg-conn-359) 0/53248/53248/9223372036854775807 (res/actual/peak/limit)
xtdb-1       | 
xtdb-1       | 00:40:40 | ERROR xtdb.indexer.LogProcessor | Ingestion stopped: error processing log record at id 4968106.
xtdb-1       | java.lang.IndexOutOfBoundsException: index: 504, length: 1 (expected: range(0, 504))
xtdb-1       |  at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:299)
xtdb-1       |  at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:285)
xtdb-1       |  at org.apache.arrow.memory.ArrowBuf.getByte(ArrowBuf.java:487)
xtdb-1       |  at org.apache.arrow.vector.BaseVariableWidthVector.isSet(BaseVariableWidthVector.java:967)
xtdb-1       |  at org.apache.arrow.vector.BaseVariableWidthVector.isNull(BaseVariableWidthVector.java:956)
xtdb-1       |  at xtdb.vector.ValueVectorReader.isNull(ValueVectorReader.java:99)
xtdb-1       |  at xtdb.vector.ValueVectorReader.hashCode(ValueVectorReader.java:89)
xtdb-1       |  at xtdb.arrow.VectorReader$Companion$OldToNewAdapter.hashCode(VectorReader.kt:197)
xtdb-1       |  at xtdb.util.HyperLogLog.add(HyperLogLog.kt:35)
xtdb-1       |  at xtdb.util.HyperLogLog.add$default(HyperLogLog.kt:35)
xtdb-1       |  at xtdb.indexer.HllCalculator.update$lambda$2(HllCalculator.kt:22)
xtdb-1       |  at xtdb.indexer.HllCalculator.update$lambda$3(HllCalculator.kt:19)
xtdb-1       |  at java.base/java.util.HashMap.compute(HashMap.java:1324)
xtdb-1       |  at xtdb.indexer.HllCalculator.update(HllCalculator.kt:19)
xtdb-1       |  at xtdb.indexer.LiveTable$Tx.commit(LiveTable.kt:129)
xtdb-1       |  at xtdb.indexer.live_index.LiveIndex$reify__13860$fn__13864.invoke(live_index.clj:93)
xtdb-1       |  at xtdb.indexer.live_index.LiveIndex$reify__13860.commit(live_index.clj:91)
xtdb-1       |  at xtdb.indexer.Indexer$fn__23078.invoke(indexer.clj:750)
xtdb-1       |  at xtdb.indexer.Indexer.indexTx(indexer.clj:678)
xtdb-1       |  at xtdb.indexer.LogProcessor$processRecords$1.invokeSuspend(LogProcessor.kt:124)
xtdb-1       |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
xtdb-1       |  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
xtdb-1       |  at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
xtdb-1       |  at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
xtdb-1       |  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
xtdb-1       |  at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
xtdb-1       |  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
xtdb-1       |  at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
xtdb-1       |  at xtdb.indexer.LogProcessor.processRecords(LogProcessor.kt:103)
xtdb-1       |  at xtdb.api.log.LocalLog$subscribe$subscription$1.invokeSuspend$lambda$0(LocalLog.kt:239)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:48)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:40)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
xtdb-1       |  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
xtdb-1       |  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:157)
xtdb-1       |  at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:39)
xtdb-1       |  at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:36)
xtdb-1       |  at xtdb.api.log.LocalLog$subscribe$subscription$1.invokeSuspend(LocalLog.kt:239)
xtdb-1       |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
xtdb-1       |  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:35)
xtdb-1       |  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:101)
xtdb-1       |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
xtdb-1       |  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
xtdb-1       |  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
xtdb-1       |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
xtdb-1       |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
xtdb-1       |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
xtdb-1       | 00:40:40 | ERROR xtdb.indexer.LogProcessor | XTDB transaction processing has encountered an unrecoverable error and has been stopped to prevent corruption of your data.
xtdb-1       | This node has also been marked unhealthy, so if it is running within a container orchestration system (e.g. Kubernetes) it should be restarted shortly.
xtdb-1       | 
xtdb-1       | Please see https://docs.xtdb.com/ops/troubleshooting#ingestion-stopped for more information and next steps.
```

**Comment by seancorfield** [comment]
This is actually causing `next.jdbc`'s test suite to fail in CI https://github.com/seancorfield/next-jdbc/actions/runs/14075085540/job/39416550841 so it might be worse than before?

**Comment by jarohen** [comment]
Thanks @seancorfield - I don't think I've pushed 2.0.0-SNAPSHOT in a while, have done so now.

Would you prefer to run tests against latest release (currently 2.0.0-beta6) rather than snapshot?

**Comment by seancorfield** [comment]
@jarohen Currently, `next.jdbc` tests against the nightly Docker image for XTDB -- what should I change this to in my Docker compose file:

```
    image: ghcr.io/xtdb/xtdb:nightly
```

**Comment by seancorfield** [comment]
FWIW, with the beta6 client deps and the nightly Docker image, I still get the same error (usually on the second test run).

**Comment by seancorfield** [comment]
I switched the Docker image to `latest` and confirmed that pulls beta6. With a beta6 Docker image and a beta6 client dep, I have not managed to reproduce this error.

I guess I was under the (mistaken) impression that you built nightly Docker images **and** Sonatype JARs. I'll stick with `latest` (Docker) and beta6 client deps for now and re-enable GH Actions for testing XTDB in `next.jdbc`.

**Comment by refset** [comment]
Apologies for the confusion @seancorfield - and thank you for persevering with the testing 🙏
